version: "3.8"

services:

  mlo_frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    image: florian06/mlo-backend:1.1
    restart: always
    ports:
      - "${FRONTEND_PORT_EXTERNAL}:80"

  mlo_backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    image: florian06/mlo-backend:1.1
    restart: always
    volumes:
      - ./properties/application-backend.yml:/devops/properties/application-backend.yml
    depends_on:
      - ${MYSQL_CONTAINER_NAME}
    ports:
      - "${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT_INTERNAL}"
    environment:
      - DB_NAME=${MYSQL_HOSTNAME}
      - DB_PORT=${MYSQL_HOST_PORT}
      - DB_USERNAME=${MYSQL_PASSWORD}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${MYSQL_HOSTNAME}
      - BACKEND_PORT=${BACKEND_PORT_EXTERNAL}
networks:
  default:
    external:
      name: mlo_network
