version: '3.8'
services:

  mlo-mysql:
    image: mysql:5.6
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_CONTAINER_PORT}
    restart: unless-stopped
    volumes:
      - ${MYSQL_DATA_VOLUME}:/var/lib/mysql
      - ${MYSQL_CONFIG_VOLUME}:/etc/mysql
      - ${MYSQL_LOG_VOLUME}:/var/log/mysql
    hostname: ${MYSQL_HOSTNAME}
    networks:
      mlo_network:

networks:
  mlo_network:
    external: true
